openapi: 3.0.1
info:
  title: Hippo.Web
  version: "1.0"
servers:
- url: /
security:
- Bearer: []
paths:
  /api/account:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateAccountCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateAccountCommand'
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
          description: Success
      tags:
      - Account
  /api/account/createtoken:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTokenCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateTokenCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateTokenCommand'
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/TokenInfo'
            application/json:
              schema:
                $ref: '#/components/schemas/TokenInfo'
            text/json:
              schema:
                $ref: '#/components/schemas/TokenInfo'
          description: Success
      tags:
      - Account
  /api/app:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AppsVm'
            application/json:
              schema:
                $ref: '#/components/schemas/AppsVm'
            text/json:
              schema:
                $ref: '#/components/schemas/AppsVm'
          description: Success
      tags:
      - App
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAppCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateAppCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateAppCommand'
      responses:
        "200":
          content:
            text/plain:
              schema:
                format: uuid
                type: string
            application/json:
              schema:
                format: uuid
                type: string
            text/json:
              schema:
                format: uuid
                type: string
          description: Success
      tags:
      - App
  /api/app/export:
    get:
      responses:
        "200":
          description: Success
      tags:
      - App
  /api/app/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          description: Success
      tags:
      - App
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAppCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateAppCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateAppCommand'
      responses:
        "200":
          description: Success
      tags:
      - App
  /api/certificate:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/CertificatesVm'
            application/json:
              schema:
                $ref: '#/components/schemas/CertificatesVm'
            text/json:
              schema:
                $ref: '#/components/schemas/CertificatesVm'
          description: Success
      tags:
      - Certificate
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCertificateCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateCertificateCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateCertificateCommand'
      responses:
        "200":
          content:
            text/plain:
              schema:
                format: uuid
                type: string
            application/json:
              schema:
                format: uuid
                type: string
            text/json:
              schema:
                format: uuid
                type: string
          description: Success
      tags:
      - Certificate
  /api/certificate/export:
    get:
      responses:
        "200":
          description: Success
      tags:
      - Certificate
  /api/certificate/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          description: Success
      tags:
      - Certificate
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCertificateCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateCertificateCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateCertificateCommand'
      responses:
        "200":
          description: Success
      tags:
      - Certificate
  /api/channel:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ChannelsVm'
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelsVm'
            text/json:
              schema:
                $ref: '#/components/schemas/ChannelsVm'
          description: Success
      tags:
      - Channel
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChannelCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateChannelCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateChannelCommand'
      responses:
        "200":
          content:
            text/plain:
              schema:
                format: uuid
                type: string
            application/json:
              schema:
                format: uuid
                type: string
            text/json:
              schema:
                format: uuid
                type: string
          description: Success
      tags:
      - Channel
  /api/channel/{channelId}:
    get:
      parameters:
      - explode: false
        in: path
        name: channelId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/ChannelDto'
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelDto'
            text/json:
              schema:
                $ref: '#/components/schemas/ChannelDto'
          description: Success
      tags:
      - Channel
  /api/channel/export:
    get:
      responses:
        "200":
          description: Success
      tags:
      - Channel
  /api/channel/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          description: Success
      tags:
      - Channel
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateChannelCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateChannelCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateChannelCommand'
      responses:
        "200":
          description: Success
      tags:
      - Channel
  /api/channel/{channelId}/environment-variables:
    put:
      parameters:
      - explode: false
        in: path
        name: channelId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateChannelEnvironmentVariablesCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateChannelEnvironmentVariablesCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateChannelEnvironmentVariablesCommand'
      responses:
        "200":
          description: Success
      tags:
      - Channel
  /api/channel/logs/{channelId}:
    get:
      parameters:
      - explode: false
        in: path
        name: channelId
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/GetChannelLogsVm'
            application/json:
              schema:
                $ref: '#/components/schemas/GetChannelLogsVm'
            text/json:
              schema:
                $ref: '#/components/schemas/GetChannelLogsVm'
          description: Success
      tags:
      - Channel
  /api/environmentvariable:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/EnvironmentVariablesVm'
            application/json:
              schema:
                $ref: '#/components/schemas/EnvironmentVariablesVm'
            text/json:
              schema:
                $ref: '#/components/schemas/EnvironmentVariablesVm'
          description: Success
      tags:
      - EnvironmentVariable
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateEnvironmentVariableCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateEnvironmentVariableCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateEnvironmentVariableCommand'
      responses:
        "200":
          content:
            text/plain:
              schema:
                format: uuid
                type: string
            application/json:
              schema:
                format: uuid
                type: string
            text/json:
              schema:
                format: uuid
                type: string
          description: Success
      tags:
      - EnvironmentVariable
  /api/environmentvariable/export:
    get:
      responses:
        "200":
          description: Success
      tags:
      - EnvironmentVariable
  /api/environmentvariable/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          description: Success
      tags:
      - EnvironmentVariable
    put:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateEnvironmentVariableCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateEnvironmentVariableCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateEnvironmentVariableCommand'
      responses:
        "200":
          description: Success
      tags:
      - EnvironmentVariable
  /api/jobstatus:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                items:
                  $ref: '#/components/schemas/ChannelJobStatus'
                type: array
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ChannelJobStatus'
                type: array
            text/json:
              schema:
                items:
                  $ref: '#/components/schemas/ChannelJobStatus'
                type: array
          description: Success
      tags:
      - JobStatus
  /api/revision:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/RevisionsVm'
            application/json:
              schema:
                $ref: '#/components/schemas/RevisionsVm'
            text/json:
              schema:
                $ref: '#/components/schemas/RevisionsVm'
          description: Success
      tags:
      - Revision
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRevisionCommand'
          text/json:
            schema:
              $ref: '#/components/schemas/RegisterRevisionCommand'
          application/*+json:
            schema:
              $ref: '#/components/schemas/RegisterRevisionCommand'
      responses:
        "200":
          description: Success
      tags:
      - Revision
  /api/revision/export:
    get:
      responses:
        "200":
          description: Success
      tags:
      - Revision
  /api/revision/{id}:
    delete:
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          format: uuid
          type: string
        style: simple
      responses:
        "200":
          description: Success
      tags:
      - Revision
  /api/storage:
    get:
      parameters:
      - explode: true
        in: query
        name: queryString
        required: false
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: offset
        required: false
        schema:
          format: int64
          type: integer
        style: form
      - explode: true
        in: query
        name: limit
        required: false
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/StorageList'
            application/json:
              schema:
                $ref: '#/components/schemas/StorageList'
            text/json:
              schema:
                $ref: '#/components/schemas/StorageList'
          description: Success
      tags:
      - Storage
components:
  schemas:
    AppChannelSummary:
      additionalProperties: false
      example:
        name: name
        activeRevisionNumber: activeRevisionNumber
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          format: uuid
          type: string
        name:
          type: string
        activeRevisionNumber:
          nullable: true
          type: string
      required:
      - id
      - name
      type: object
    AppDto:
      additionalProperties: false
      example:
        channels:
        - name: name
          activeRevisionNumber: activeRevisionNumber
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - name: name
          activeRevisionNumber: activeRevisionNumber
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        name: name
        description: description
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        storageId: storageId
      properties:
        id:
          format: uuid
          type: string
        name:
          type: string
        storageId:
          type: string
        description:
          nullable: true
          type: string
        channels:
          items:
            $ref: '#/components/schemas/AppChannelSummary'
          type: array
      required:
      - channels
      - id
      - name
      - storageId
      type: object
    AppSummaryDto:
      additionalProperties: false
      example:
        channels:
        - name: name
          activeRevisionNumber: activeRevisionNumber
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - name: name
          activeRevisionNumber: activeRevisionNumber
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        name: name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        storageId: storageId
      properties:
        id:
          format: uuid
          type: string
        name:
          type: string
        storageId:
          type: string
        channels:
          items:
            $ref: '#/components/schemas/AppChannelSummary'
          type: array
      required:
      - channels
      - id
      - name
      - storageId
      type: object
    AppsVm:
      additionalProperties: false
      example:
        apps:
        - channels:
          - name: name
            activeRevisionNumber: activeRevisionNumber
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - name: name
            activeRevisionNumber: activeRevisionNumber
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          name: name
          description: description
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          storageId: storageId
        - channels:
          - name: name
            activeRevisionNumber: activeRevisionNumber
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - name: name
            activeRevisionNumber: activeRevisionNumber
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          name: name
          description: description
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          storageId: storageId
      properties:
        apps:
          items:
            $ref: '#/components/schemas/AppDto'
          type: array
      required:
      - apps
      type: object
    CertificateDto:
      additionalProperties: false
      example:
        privateKey: privateKey
        channels:
        - appSummary:
            channels:
            - name: name
              activeRevisionNumber: activeRevisionNumber
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - name: name
              activeRevisionNumber: activeRevisionNumber
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            storageId: storageId
          environmentVariables:
          - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            value: value
            channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            key: key
          - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            value: value
            channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            key: key
          appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          domain: domain
          name: name
          certificate: null
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          revisionSelectionStrategy: null
          activeRevision:
            components:
            - route: route
              name: name
              channel: channel
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              source: source
              type: type
            - route: route
              name: name
              channel: channel
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              source: source
              type: type
            revisionNumber: revisionNumber
            appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          rangeRule: rangeRule
        - appSummary:
            channels:
            - name: name
              activeRevisionNumber: activeRevisionNumber
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - name: name
              activeRevisionNumber: activeRevisionNumber
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            storageId: storageId
          environmentVariables:
          - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            value: value
            channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            key: key
          - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            value: value
            channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            key: key
          appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          domain: domain
          name: name
          certificate: null
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          revisionSelectionStrategy: null
          activeRevision:
            components:
            - route: route
              name: name
              channel: channel
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              source: source
              type: type
            - route: route
              name: name
              channel: channel
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              source: source
              type: type
            revisionNumber: revisionNumber
            appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          rangeRule: rangeRule
        name: name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        publicKey: publicKey
      properties:
        id:
          format: uuid
          type: string
        name:
          type: string
        publicKey:
          type: string
        privateKey:
          type: string
        channels:
          items:
            $ref: '#/components/schemas/ChannelDto'
          type: array
      required:
      - channels
      - id
      - name
      - privateKey
      - publicKey
      type: object
    CertificatesVm:
      additionalProperties: false
      example:
        certificates:
        - privateKey: privateKey
          channels:
          - appSummary:
              channels:
              - name: name
                activeRevisionNumber: activeRevisionNumber
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              - name: name
                activeRevisionNumber: activeRevisionNumber
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              storageId: storageId
            environmentVariables:
            - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              value: value
              channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              key: key
            - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              value: value
              channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              key: key
            appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            domain: domain
            name: name
            certificate: null
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            revisionSelectionStrategy: null
            activeRevision:
              components:
              - route: route
                name: name
                channel: channel
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                source: source
                type: type
              - route: route
                name: name
                channel: channel
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                source: source
                type: type
              revisionNumber: revisionNumber
              appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            rangeRule: rangeRule
          - appSummary:
              channels:
              - name: name
                activeRevisionNumber: activeRevisionNumber
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              - name: name
                activeRevisionNumber: activeRevisionNumber
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              storageId: storageId
            environmentVariables:
            - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              value: value
              channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              key: key
            - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              value: value
              channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              key: key
            appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            domain: domain
            name: name
            certificate: null
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            revisionSelectionStrategy: null
            activeRevision:
              components:
              - route: route
                name: name
                channel: channel
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                source: source
                type: type
              - route: route
                name: name
                channel: channel
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                source: source
                type: type
              revisionNumber: revisionNumber
              appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            rangeRule: rangeRule
          name: name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          publicKey: publicKey
        - privateKey: privateKey
          channels:
          - appSummary:
              channels:
              - name: name
                activeRevisionNumber: activeRevisionNumber
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              - name: name
                activeRevisionNumber: activeRevisionNumber
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              storageId: storageId
            environmentVariables:
            - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              value: value
              channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              key: key
            - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              value: value
              channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              key: key
            appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            domain: domain
            name: name
            certificate: null
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            revisionSelectionStrategy: null
            activeRevision:
              components:
              - route: route
                name: name
                channel: channel
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                source: source
                type: type
              - route: route
                name: name
                channel: channel
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                source: source
                type: type
              revisionNumber: revisionNumber
              appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            rangeRule: rangeRule
          - appSummary:
              channels:
              - name: name
                activeRevisionNumber: activeRevisionNumber
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              - name: name
                activeRevisionNumber: activeRevisionNumber
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              name: name
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              storageId: storageId
            environmentVariables:
            - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              value: value
              channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              key: key
            - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              value: value
              channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              key: key
            appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            domain: domain
            name: name
            certificate: null
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            revisionSelectionStrategy: null
            activeRevision:
              components:
              - route: route
                name: name
                channel: channel
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                source: source
                type: type
              - route: route
                name: name
                channel: channel
                id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
                source: source
                type: type
              revisionNumber: revisionNumber
              appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            rangeRule: rangeRule
          name: name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          publicKey: publicKey
      properties:
        certificates:
          items:
            $ref: '#/components/schemas/CertificateDto'
          type: array
      required:
      - certificates
      type: object
    ChannelDto:
      additionalProperties: false
      example:
        appSummary:
          channels:
          - name: name
            activeRevisionNumber: activeRevisionNumber
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          - name: name
            activeRevisionNumber: activeRevisionNumber
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          name: name
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          storageId: storageId
        environmentVariables:
        - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          value: value
          channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          key: key
        - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          value: value
          channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          key: key
        appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        domain: domain
        name: name
        certificate: null
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        revisionSelectionStrategy: null
        activeRevision:
          components:
          - route: route
            name: name
            channel: channel
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            source: source
            type: type
          - route: route
            name: name
            channel: channel
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            source: source
            type: type
          revisionNumber: revisionNumber
          appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        rangeRule: rangeRule
      properties:
        id:
          format: uuid
          type: string
        appId:
          format: uuid
          type: string
        name:
          type: string
        domain:
          type: string
        revisionSelectionStrategy:
          $ref: '#/components/schemas/ChannelRevisionSelectionStrategy'
        activeRevision:
          $ref: '#/components/schemas/RevisionDto'
        rangeRule:
          nullable: true
          type: string
        certificate:
          $ref: '#/components/schemas/CertificateDto'
        environmentVariables:
          items:
            $ref: '#/components/schemas/EnvironmentVariableDto'
          type: array
        appSummary:
          $ref: '#/components/schemas/AppSummaryDto'
      required:
      - appId
      - domain
      - environmentVariables
      - id
      - name
      - revisionSelectionStrategy
      type: object
    ChannelJobStatus:
      additionalProperties: false
      example:
        channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        status: null
      properties:
        channelId:
          format: uuid
          type: string
        status:
          $ref: '#/components/schemas/JobStatus'
      required:
      - channelId
      - status
      type: object
    ChannelRevisionSelectionStrategy:
      enum:
      - UseRangeRule
      - UseSpecifiedRevision
      type: string
    ChannelsVm:
      additionalProperties: false
      example:
        channels:
        - appSummary:
            channels:
            - name: name
              activeRevisionNumber: activeRevisionNumber
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - name: name
              activeRevisionNumber: activeRevisionNumber
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            storageId: storageId
          environmentVariables:
          - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            value: value
            channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            key: key
          - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            value: value
            channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            key: key
          appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          domain: domain
          name: name
          certificate: null
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          revisionSelectionStrategy: null
          activeRevision:
            components:
            - route: route
              name: name
              channel: channel
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              source: source
              type: type
            - route: route
              name: name
              channel: channel
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              source: source
              type: type
            revisionNumber: revisionNumber
            appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          rangeRule: rangeRule
        - appSummary:
            channels:
            - name: name
              activeRevisionNumber: activeRevisionNumber
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            - name: name
              activeRevisionNumber: activeRevisionNumber
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            name: name
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            storageId: storageId
          environmentVariables:
          - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            value: value
            channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            key: key
          - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            value: value
            channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            key: key
          appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          domain: domain
          name: name
          certificate: null
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          revisionSelectionStrategy: null
          activeRevision:
            components:
            - route: route
              name: name
              channel: channel
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              source: source
              type: type
            - route: route
              name: name
              channel: channel
              id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
              source: source
              type: type
            revisionNumber: revisionNumber
            appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          rangeRule: rangeRule
      properties:
        channels:
          items:
            $ref: '#/components/schemas/ChannelDto'
          type: array
      required:
      - channels
      type: object
    CreateAccountCommand:
      additionalProperties: false
      example:
        password: password
        userName: userName
      properties:
        userName:
          type: string
        password:
          type: string
      required:
      - password
      - userName
      type: object
    CreateAppCommand:
      additionalProperties: false
      example:
        name: name
        storageId: storageId
      properties:
        name:
          type: string
        storageId:
          type: string
      required:
      - name
      - storageId
      type: object
    CreateCertificateCommand:
      additionalProperties: false
      example:
        privateKey: privateKey
        name: name
        publicKey: publicKey
      properties:
        name:
          type: string
        publicKey:
          type: string
        privateKey:
          type: string
      required:
      - name
      - privateKey
      - publicKey
      type: object
    CreateChannelCommand:
      additionalProperties: false
      example:
        appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        domain: domain
        certificateId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        name: name
        revisionSelectionStrategy: null
        rangeRule: rangeRule
        activeRevisionId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        appId:
          format: uuid
          type: string
        name:
          type: string
        domain:
          nullable: true
          type: string
        revisionSelectionStrategy:
          $ref: '#/components/schemas/ChannelRevisionSelectionStrategy'
        rangeRule:
          nullable: true
          type: string
        activeRevisionId:
          format: uuid
          nullable: true
          type: string
        certificateId:
          format: uuid
          nullable: true
          type: string
      required:
      - appId
      - name
      - revisionSelectionStrategy
      type: object
    CreateEnvironmentVariableCommand:
      additionalProperties: false
      example:
        value: value
        key: key
        channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        key:
          type: string
        value:
          type: string
        channelId:
          format: uuid
          type: string
      required:
      - channelId
      - key
      - value
      type: object
    CreateTokenCommand:
      additionalProperties: false
      example:
        password: password
        userName: userName
      properties:
        userName:
          type: string
        password:
          type: string
      required:
      - password
      - userName
      type: object
    EnvironmentVariableDto:
      additionalProperties: false
      example:
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        value: value
        channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        key: key
      properties:
        id:
          format: uuid
          type: string
        channelId:
          format: uuid
          type: string
        key:
          type: string
        value:
          type: string
      required:
      - channelId
      - id
      - key
      - value
      type: object
    EnvironmentVariablesVm:
      additionalProperties: false
      example:
        environmentVariables:
        - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          value: value
          channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          key: key
        - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          value: value
          channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          key: key
      properties:
        environmentVariables:
          items:
            $ref: '#/components/schemas/EnvironmentVariableDto'
          type: array
      required:
      - environmentVariables
      type: object
    GetChannelLogsVm:
      additionalProperties: false
      example:
        logs:
        - logs
        - logs
      properties:
        logs:
          items:
            type: string
          type: array
      required:
      - logs
      type: object
    JobStatus:
      enum:
      - Unknown
      - Pending
      - Running
      - Dead
      type: string
    RegisterRevisionCommand:
      additionalProperties: false
      example:
        revisionNumber: revisionNumber
        appStorageId: appStorageId
      properties:
        appStorageId:
          type: string
        revisionNumber:
          type: string
      required:
      - appStorageId
      - revisionNumber
      type: object
    RevisionComponentDto:
      additionalProperties: false
      example:
        route: route
        name: name
        channel: channel
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        source: source
        type: type
      properties:
        id:
          format: uuid
          type: string
        source:
          type: string
        name:
          type: string
        route:
          nullable: true
          type: string
        channel:
          nullable: true
          type: string
        type:
          nullable: true
          type: string
      required:
      - id
      - name
      - source
      type: object
    RevisionDto:
      additionalProperties: false
      example:
        components:
        - route: route
          name: name
          channel: channel
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          source: source
          type: type
        - route: route
          name: name
          channel: channel
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          source: source
          type: type
        revisionNumber: revisionNumber
        appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          format: uuid
          type: string
        appId:
          format: uuid
          type: string
        revisionNumber:
          type: string
        components:
          items:
            $ref: '#/components/schemas/RevisionComponentDto'
          readOnly: true
          type: array
      required:
      - appId
      - components
      - id
      - revisionNumber
      type: object
    RevisionsVm:
      additionalProperties: false
      example:
        revisions:
        - components:
          - route: route
            name: name
            channel: channel
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            source: source
            type: type
          - route: route
            name: name
            channel: channel
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            source: source
            type: type
          revisionNumber: revisionNumber
          appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        - components:
          - route: route
            name: name
            channel: channel
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            source: source
            type: type
          - route: route
            name: name
            channel: channel
            id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
            source: source
            type: type
          revisionNumber: revisionNumber
          appId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        revisions:
          items:
            $ref: '#/components/schemas/RevisionDto'
          type: array
      required:
      - revisions
      type: object
    StorageList:
      additionalProperties: false
      example:
        storages:
        - storages
        - storages
      properties:
        storages:
          items:
            type: string
          type: array
      required:
      - storages
      type: object
    TokenInfo:
      additionalProperties: false
      example:
        expiration: 2000-01-23T04:56:07.000+00:00
        token: token
      properties:
        token:
          nullable: true
          type: string
        expiration:
          format: date-time
          readOnly: true
          type: string
      type: object
    UpdateAppCommand:
      additionalProperties: false
      example:
        name: name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        storageId: storageId
      properties:
        id:
          format: uuid
          type: string
        name:
          type: string
        storageId:
          type: string
      required:
      - id
      - name
      - storageId
      type: object
    UpdateCertificateCommand:
      additionalProperties: false
      example:
        privateKey: privateKey
        name: name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        publicKey: publicKey
      properties:
        id:
          format: uuid
          type: string
        name:
          type: string
        publicKey:
          type: string
        privateKey:
          type: string
      required:
      - id
      - name
      - privateKey
      - publicKey
      type: object
    UpdateChannelCommand:
      additionalProperties: false
      example:
        domain: domain
        certificateId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        name: name
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        revisionSelectionStrategy: null
        rangeRule: rangeRule
        activeRevisionId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        id:
          format: uuid
          type: string
        name:
          type: string
        domain:
          type: string
        revisionSelectionStrategy:
          $ref: '#/components/schemas/ChannelRevisionSelectionStrategy'
        rangeRule:
          nullable: true
          type: string
        activeRevisionId:
          format: uuid
          nullable: true
          type: string
        certificateId:
          format: uuid
          nullable: true
          type: string
      required:
      - domain
      - id
      - name
      - revisionSelectionStrategy
      type: object
    UpdateChannelEnvironmentVariablesCommand:
      additionalProperties: false
      example:
        environmentVariables:
        - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          value: value
          key: key
        - id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
          value: value
          key: key
        channelId: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
      properties:
        channelId:
          format: uuid
          type: string
        environmentVariables:
          items:
            $ref: '#/components/schemas/UpdateEnvironmentVariableDto'
          nullable: true
          type: array
      type: object
    UpdateEnvironmentVariableCommand:
      additionalProperties: false
      example:
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        value: value
        key: key
      properties:
        id:
          format: uuid
          type: string
        key:
          type: string
        value:
          type: string
      required:
      - id
      - key
      - value
      type: object
    UpdateEnvironmentVariableDto:
      additionalProperties: false
      example:
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        value: value
        key: key
      properties:
        id:
          format: uuid
          type: string
        key:
          type: string
        value:
          type: string
      required:
      - id
      - key
      - value
      type: object
  securitySchemes:
    Bearer:
      description: "JWT Authorization header using the Bearer scheme. Example: \"\
        Authorization: Bearer {token}\""
      in: header
      name: Authorization
      type: apiKey
